services:

  backend:

    image: ${DOCKER_SPRING_IMAGE}

    container_name: spring-container

    restart: always

    environment:

      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/coffee

      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}

      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}

    ports:
      - "9000:9000"

    networks:
      - coffee-network


  frontend:

    image: ${DOCKER_REACT_IMAGE}

    container_name: react-container

    restart: always

    depends_on:
      - backend

    ports:
      - "80:80"

    networks:
      - coffee-network


networks:

  coffee-network: