services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: My@Sql01
      MYSQL_DATABASE: coffee
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: 
      context: ./spring_coffee
      dockerfile: DockerfileSpring
    container_name: spring-container
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coffee
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: My@Sql01
    ports:
      - "9000:9000"

  nginx:
    build:
      context: ./react_coffee
      dockerfile: DockerfileReact
    container_name: nginx-container
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql-data: