spring.application.name=Coffee
server.port=9000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.servlet.session.timeout=120m
jwt.secret=my-secret-key-my-secret-key-my-secret-key
jwt.expiration=3600000
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
server.tomcat.threads.max=50
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000