name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # React build
      - name: Build React
        run: |
          cd react_coffee
          npm install
          npm run build

      # Spring build
      - name: Build Spring
        run: |
          cd spring_coffee
          #mvn clean package -DskipTests
          ./mvnw clean package -DskipTests

      # Docker build
      - name: Docker build
        run: docker-compose build

      # EC2 배포
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/project
            git pull
            docker-compose down
            docker-compose up -d --build